// Generated by CodiumAI
import React from "react";
import { render } from "@testing-library/react";
import App from "./App";

jest.mock("./Api", () => ({
  getLocalAccessToken: jest.fn(),
}));
jest.mock("react-redux");

describe("App", () => {
  // Tests that the App component renders without errors
  it("should render without errors", () => {
    render(<App />);
  });
});
